#######################################################################
    
    [id]
    object_name = '2M2236'
    run_labels = [
        'Piette',
        'G395H',
        'cloud-free',
        '2024-02-27',
        'continuation'
        ]

#######################################################################

    [configuration.observation.resolved] # just the presence implies observation mode is "resolved"
    # there are no resolved-specific options but they would go here if they existed
    # here is what the transit option might look like:

    # [configuration.observation.transit.star]
    # path_to_spectrum = 'None'
    # effective_temperature = 6516.0
    # radius_relative_to_solar = 1.86
    # orbital_semimajor_axis_in_AU = 600.0

    [configuration.radiative_transfer_scheme.two_stream]
    # [placeholder]

    [configuration.wavelength_coordinates.model_from_data]
    data_filepath = '/rhome/arthura/APOLLO/data/2M2236b_NIRSpec_G395H_R500_APOLLO.dat'
    convolution_factor = 1
    binning_factor = 1

    [configuration.reference_data.molecular_crosssections]
    directory = '/rhome/arthura/bigdata/APOLLO_data/Opacities_0v10'
    forward_model_table_name = 'jwst50k'
    forward_model_table_resolution_degradation_factor = 1 # 1 -> no degradation
    effective_temperature_table_name = 'lores'

#######################################################################

    [configuration.fitting]
    results_output_directory = '/rhome/arthura/bigdata/samples'
    run_in_parallel_mode = true

    [configuration.fitting.dynesty]  # sampler-specific configurations
        checkpoint_filepath = '/rhome/arthura/bigdata/samples/2M2236.Piette.G395H.cloud-free.2024-02-27.dynesty_checkpoint.dat'
        number_of_live_points = 1000
        number_of_iterations = 500000
        sampling_type = 'rwalk'

    [configuration.fitting.priors]
        uniform_mass_prior = [ 0.5, 1e15 ]

#######################################################################

    [model.atmosphere.fundamental.use_hydrostatic_equilibrium]
        # i.e. given a radius, gravity, and pressures, you can calculate the altitude as a function of pressure
        radius_in_Earth_units = 11.44 # { MLE=11.44, Mu=19.41, Sigma=0.02, Min=5.00, Max=50.00, Lower=0.02, Higher=0.02 }
        log_surface_gravity_in_cgs = -4.56 # { MLE=-4.56, Mu=-4.56, Sigma=0.01, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }

    [model.atmosphere.vertical.pressure_profile.uniform_in_log_pressure]
        minimum_pressure_in_log_bars = 0.0
        maximum_pressure_in_log_bars = 3.0

    [model.atmosphere.vertical.thermal_profile.piette]
        T_m4  =  433.1 # { MLE=433.095329,  Mu=1967.14, Sigma=5.42,  Min=100.00, Max=4000.00, Lower=7.41,   Higher=5.42 }
        T_m3  =  481.2 # { MLE=481.868528,  Mu=3627.54, Sigma=98.41, Min=100.00, Max=4000.00, Lower=148.57, Higher=98.41 }
        T_m2  =  557.8 # { MLE=557.843874,  Mu=3792.56, Sigma=34.27, Min=100.00, Max=4000.00, Lower=25.99,  Higher=34.27 }
        T_m1  =  705.2 # { MLE=705.230919,  Mu=1967.14, Sigma=5.42,  Min=100.00, Max=4000.00, Lower=7.41,   Higher=5.42 }
        T_0   = 1127.6 # { MLE=1127.597652, Mu=3627.54, Sigma=98.41, Min=100.00, Max=4000.00, Lower=148.57, Higher=98.41 }
        T_0p5 = 1412.6 # { MLE=1412.647250, Mu=3792.56, Sigma=34.27, Min=100.00, Max=4000.00, Lower=25.99,  Higher=34.27 }
        T_1   = 1781.5 # { MLE=1781.538772, Mu=3792.56, Sigma=34.27, Min=100.00, Max=4000.00, Lower=25.99,  Higher=34.27 }
        T_1p5 = 2382.7 # { MLE=2382.715910, Mu=3792.56, Sigma=34.27, Min=100.00, Max=4000.00, Lower=25.99,  Higher=34.27 }
        T_2   = 3440.9 # { MLE=3440.880515, Mu=3792.56, Sigma=34.27, Min=100.00, Max=4000.00, Lower=25.99,  Higher=34.27 }
        T_2p5 = 4000.0 # { MLE=4000.000000, Mu=3792.56, Sigma=34.27, Min=100.00, Max=4000.00, Lower=25.99,  Higher=34.27 }

    [model.atmosphere.material.rayleigh_scattering_with_uniform_mixing_ratios] # from_crosssections?
    # implies that there is a function "rayleigh_scattering" in the module "material"
    h2 =       'filler' # { MLE=-6.96, Mu=-6.96, Sigma=0.01, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }
    co =       -3.83    # { MLE=-3.83, Mu=-3.52, Sigma=0.04, Min=-12.00, Max=-1.00, Lower=0.04, Higher=0.04 }
    co2 =      -6.96    # { MLE=-6.96, Mu=-6.96, Sigma=0.01, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }
    ch4 =      -3.54    # { MLE=-3.54, Mu=-3.54, Sigma=0.01, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }
    Lupu_alk = -5.46    # { MLE=-5.46, Mu=-6.25, Sigma=0.03, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }
    h2s =      -4.56    # { MLE=-4.56, Mu=-4.56, Sigma=0.01, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }
    nh3 =      -3.54    # { MLE=-3.54, Mu=-3.54, Sigma=0.01, Min=-12.00, Max=-1.00, Lower=0.01, Higher=0.01 }

    [model.atmosphere.material.clouds_with_powerlaw_opacity]
    powerlaw_exponent            = -5.29 # { MLE = -5.29, Mu = -5.29, Sigma=0.01, Min=-10.00, Max=10.00, Lower=0.01, Higher=0.01 }
    minimum_pressure_in_log_bars =  2.47 # { MLE =  2.47, Mu = 2.47, Sigma=0.01, Min=-6.00, Max=2.50, Lower=0.01, Higher=0.01 }
    thickness_in_log_bars        =  0.02 # { MLE =  0.02, Mu = 0.02, Sigma=0.01, Min=0.00, Max=6.50, Lower=0.01, Higher=0.01 }
    log_optical_depth_at_1um     = -0.31 # { MLE = -0.31, Mu = -0.31, Sigma=0.01, Min=-3.00, Max=3.00, Lower=0.01, Higher=0.01 }
    single_scattering_albedo     =  0.40 # { MLE =  0.40, Mu = 0.40, Sigma=0.01, Min=0.00, Max=0.999, Lower=0.01, Higher=0.01 }
    filling_factor               =  0.42 # { MLE =  0.42, Mu = 0.42, Sigma=0.01, Min=0.00, Max=1.00, Lower=0.01, Higher=0.01 }

    [model.observation]
    # idea: if item is not indented, assume it's its own function
    # e.g. model/observation.py has a function called "normalize_continuum" that takes a bool
    # there may be another protocol for "observation" functions, e.g. functions take a model spectrum output
    # and return another model spectrum output with the same shape
    # otherwise, assume it's a nested function, or a function that can have multiple components
    normalize_continuum = false # or just omit?
    uniform_wavelength_shift_in_nm = 0.00 # { MLE=0.00,   Mu=4.15,   Sigma=0.01, Min=-5.00,   Max=5.00, Lower=0.09, Higher=0.00 }
    white_noise_variance = -50.65 # { MLE=-10.00, Mu=-10.00, Sigma=0.10, Min=-100.00, Max=5.00, Lower=0.00, Higher=0.00 }

    [model.observation.scale_flux_by_constant_factor]
        G395H_ch1 = {wavelength_start=0.75, wavelength_end=1.25, factor = 1.00 } # { MLE=1.00,   Mu=1.00,   Sigma=0.01, Min=0.75,    Max=1.25, Lower=0.01, Higher=0.01 }
        G395H_ch2 = {wavelength_start=0.75, wavelength_end=1.25, factor = 1.00 } # { MLE=1.00,   Mu=1.00,   Sigma=0.01, Min=0.75,    Max=1.25, Lower=0.01, Higher=0.01 }
