# planet_radius_in_cm: float = 3.6318e9 / 2

# planet_gravity_in_cgs: float = 756.4  # cm/s^2

# log_pressures_by_level: np.ndarray[np.float64] = np.log10(pressures_by_level)

# uniform_log_abundances: dict[str, float] = {"h2o": -3.171, "ch4": -3.318}

planet_radius_in_cm = 1.8159e9
planet_gravity_in_cgs = 756.4
