[metadata]
model_ID = "RISOTTO_T3B_Full_retrieved"
run_date = "2025-09-25"

[fundamental_parameters] # build_default_fundamental_parameters
planet_radius = 18829858.006036125
radius_units = "meters"
log10_planet_gravity = 2.878752 # 23.26 m/s^2
gravity_units = "cm/s^2"

[pressure_profile] # build_pressure_profile_from_log_pressures
shallowest_log10_pressure = -6.0
deepest_log10_pressure =    -0.003267155486805784
units = "bar"
number_of_levels = 71

[temperature_profile.model_parameters] # build_temperature_profile -> generate_isothermal_model -> IsothermalTemperatureModelParameters
temperature = 356.7627567492193

[gas_chemistry] # build_uniform_gas_chemistry
filler_species = "h2only"

[gas_chemistry.log_mixing_ratios] # 85% H2, 15% He by molecule count
"he"  =         -4.762517193087201
"h2o" =         -2.5720540941764476
"ch4" =         -2.548399863479071

[observable_inputs]
distance_to_system =  99.9999999
distance_units = "parsec"
stellar_radius =      153_054_000
radius_units = "meters"

[reference_data]
gas_opacity_catalog_filepath = "/home/Research/Opacities_0v10/gases/wide.nc"
reference_wavelength_filename = "/home/gba8kj/Documents/Astronomy/code/potluck/user/T3B_isothermal/T3B_risotto_Full_data.nc"
